// src/app/layout.tsx
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"; 
// import { Sidebar } from "@/components/sidebar"; // Sigue comentado
import { Providers } from "@/app/Providers"; 
import Header from "@/components/Header"; // <--- DESCOMENTADO
import { ClientOnly } from "@/components/ClientOnly"; 

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "AccessPoint Control",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const sidebarWidth = "270px"; // Sigue comentado, se manejará cuando se reintroduzca Sidebar

  return (
    <html lang="es" suppressHydrationWarning className="h-full">
      <body
        className={cn(
          "h-full bg-background font-sans antialiased overflow-hidden",
          fontSans.variable
        )}
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="light" 
            disableTransitionOnChange 
            // enableSystem={false} // Mantenemos esto simple por ahora
          >
            <ClientOnly fallback={<div style={{ display: 'flex', height: '100vh' }} /> /* Fallback simple que ocupa espacio */}>
              {/* Estructura original del layout reintroducida aquí DENTRO de ClientOnly */}
              <div className="flex h-full" suppressHydrationWarning> 
                {/* <Sidebar /> */} {/* Sigue comentado */}
                
                <div 
                  className="flex-1 flex flex-col h-full" 
                  // style={{ marginLeft: sidebarWidth }} // Sigue comentado
                >
                  <Header /> 
                  
                  <main className="flex-grow overflow-y-auto">
                    {children} 
                  </main>
                </div>
              </div>
            </ClientOnly>
          </ThemeProvider>
        </Providers>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
