// Code: Definir el layout de la aplicacion
import { Inter } from "next/font/google";
import "./globals.css";

// Importar la fuente de Google Inter
const inter = Inter({ subsets: ["latin"] });

// Definir la metadata de la pagina
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Definir el layout de la aplicacion
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container mx-auto px-5 mt-4">
          {children}
          </main>
      </body>
    </html>
  );
}
